[package]
name = "learningGameInRust"
version = "0.1.0"
edition = "2021"
authors = ["Chris <christophehenry11@gmail.com"]

[dependencies]
sdl2 = { version = "0.35.2", features = ["image"] }
specs = { version = "0.18.0", features = ["specs-derive", "shred-derive"] }
rand = "0.8.5"